[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 105
skip-string-normalization = true

[tool.pylint]
max-line-length = 105
disable = "missing-function-docstring,missing-module-docstring"